name: hittps

services:
  certificator:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Certificator
    container_name: certificator
    volumes:
      - certificates:/certificates:rw

  hittps:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Hittps
    container_name: hittps
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=hittps
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificates/hittps.pfx
    volumes:
      - certificates:/certificates:ro
    depends_on:
      certificator:
        condition: service_completed_successfully

  consumer:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Consumer
    container_name: consumer
    entrypoint: /bin/bash -c /bin/init
    volumes:
      - certificates:/certificates:ro
    depends_on:
      - hittps

  cerenkov:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Cerenkov
    container_name: cerenkov
    entrypoint: /bin/bash -c /bin/compose_init
    volumes:
      - certificates:/certificates:ro
    depends_on:
      - hittps

networks:
  hittps:

volumes:
  certificates:
