name: hittps

services:
  hittps:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Hittps
    container_name: hittps
  
  cerenkov:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Cerenkov
    container_name: cerenkov
    entrypoint: /bin/sh -c /bin/compose_keep_alive
    depends_on:
      - hittps

networks:
  hittps:
