FROM alpine:latest

# Install packages
RUN apk update
RUN apk add bash
RUN apk add curl
RUN apk add jq
RUN apk add ca-certificates

# Setup bash aliases
RUN echo "alias hi='curl -s hittps/messages | jq'" > ~/.bashrc

# Provide keep alive script to keep idle container running in compose context
RUN echo 'trap "exit" SIGTERM; while true; do sleep 1; done' > /bin/compose_keep_alive
RUN chmod +x /bin/compose_keep_alive

ENTRYPOINT [ "/bin/bash" ]
