FROM alpine:latest

# Install packages
RUN apk --no-cache add \
    bash \
    openssl

# Setup bash aliases
COPY ./Certificator/make-certificate /bin/make-certificate
RUN chmod +x /bin/make-certificate

ENTRYPOINT [ "bin/bash", "-c","/bin/make-certificate" ]
