FROM alpine

# TODO: Do we need bash?
RUN apk --no-cache add \
    shunit2 \
    bash

COPY ./DeMoivre ./bin
RUN mkdir tests \
    && adduser -D shunit2 \
    && chown shunit2 tests \
    && chmod +x /bin/read-stdin /bin/entrypoint

ENV SHUNIT_COLOR=always
USER shunit2
ENTRYPOINT exec /bin/entrypoint
