#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Check that certificate exists
# TODO: Check that pem and pfx exist!
if [ ! -f /certificates/hittps.pem ]; then
    echo 'No certificate for hittps found, creating self signed certificate'
    openssl req -x509 -newkey rsa:4096 -keyout /certificates/hittps_key.pem -out /certificates/hittps.pem \
        -sha256 -days 365 -nodes -subj '/CN=hittps'
    openssl pkcs12 -export -out /certificates/hittps.pfx -inkey /certificates/hittps_key.pem \
        -in /certificates/hittps.pem -password pass:hittps
else
    echo 'Certificate already exists'
fi
